server:
  port: 8080

name: zhangxd

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

security:
  user:
    name: user
    password: password
  oauth2:
    client:
      clientId: svca-service
      clientSecret: ${security.user.password}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server
spring:
  zipkin:
    base-url: http://192.168.0.220:9411