version: '2'
services:
  rabbitmq:
      image: rabbitmq:3-management
      restart: always
      extra_hosts:
        - "registry:192.168.0.25"
        - "config:192.168.0.25"
        - "monitor:192.168.0.25"
        - "rabbitmq:192.168.0.25"
        - "auth-service:192.168.0.25"
        - "git.tiduyun.com:192.168.0.48"
      network_mode: "host"
      ports:
        - 15673:15672
  registry:
    image: spring-boot-cloud/registry
    extra_hosts:
      - "registry:192.168.0.25"
      - "config:192.168.0.25"
      - "monitor:192.168.0.25"
      - "rabbitmq:192.168.0.25"
      - "auth-service:192.168.0.25"
      - "git.tiduyun.com:192.168.0.48"
    ports:
      - "8761:8761"
  config:
    image: spring-boot-cloud/config
    extra_hosts:
      - "registry:192.168.0.25"
      - "config:192.168.0.25"
      - "monitor:192.168.0.25"
      - "rabbitmq:192.168.0.25"
      - "auth-service:192.168.0.25"
      - "git.tiduyun.com:192.168.0.48"
    network_mode: "host"
    ports:
      - "8888:8888"
  monitor:
    image: spring-boot-cloud/monitor
    extra_hosts:
      - "registry:192.168.0.25"
      - "config:192.168.0.25"
      - "monitor:192.168.0.25"
      - "rabbitmq:192.168.0.25"
      - "auth-service:192.168.0.25"
      - "git.tiduyun.com:192.168.0.48"
    ports:
      - "8040:8040"
  zipkin:
    image: spring-boot-cloud/zipkin
    extra_hosts:
      - "registry:192.168.0.25"
      - "config:192.168.0.25"
      - "monitor:192.168.0.25"
      - "rabbitmq:192.168.0.25"
      - "auth-service:192.168.0.25"
      - "git.tiduyun.com:192.168.0.48"
    ports:
      - "9411:9411"
  gateway:
    image: spring-boot-cloud/gateway
    extra_hosts:
      - "registry:192.168.0.25"
      - "config:192.168.0.25"
      - "monitor:192.168.0.25"
      - "rabbitmq:192.168.0.25"
      - "auth-service:192.168.0.25"
      - "git.tiduyun.com:192.168.0.48"
    ports:
      - "8060:8060"
  auth-service:
    image: spring-boot-cloud/auth-service
    extra_hosts:
      - "registry:192.168.0.25"
      - "config:192.168.0.25"
      - "monitor:192.168.0.25"
      - "rabbitmq:192.168.0.25"
      - "auth-service:192.168.0.25"
      - "git.tiduyun.com:192.168.0.48"
    ports:
      - "5000:5000"
  svca-service:
    image: spring-boot-cloud/svca-service
    extra_hosts:
      - "registry:192.168.0.25"
      - "config:192.168.0.25"
      - "monitor:192.168.0.25"
      - "rabbitmq:192.168.0.25"
      - "auth-service:192.168.0.25"
      - "git.tiduyun.com:192.168.0.48"
  svcb-service:
    image: spring-boot-cloud/svcb-service
    extra_hosts:
      - "registry:192.168.0.25"
      - "config:192.168.0.25"
      - "monitor:192.168.0.25"
      - "rabbitmq:192.168.0.25"
      - "auth-service:192.168.0.25"
      - "git.tiduyun.com:192.168.0.48"